(cl:in-package quadrotor_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          POS_X-VAL
          POS_X
          POS_Y-VAL
          POS_Y
          POS_Z-VAL
          POS_Z
          VEL_X-VAL
          VEL_X
          VEL_Y-VAL
          VEL_Y
          VEL_Z-VAL
          VEL_Z
          PWM_1-VAL
          PWM_1
          PWM_2-VAL
          PWM_2
          PWM_3-VAL
          PWM_3
          PWM_4-VAL
          PWM_4
          OMEGA_X-VAL
          OMEGA_X
          OMEGA_Y-VAL
          OMEGA_Y
          OMEGA_Z-VAL
          OMEGA_Z
))